version: "3.6"
services:
  api:
    build: .
    container_name: api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
